[build]
  publish="html"
  functions = "netlify/functions"
[[redirects]]
  from = "/"
  to = "/.netlify/functions/lanzou.js?url=:lanzouwmurl"
  status = 200
  force = true
  query = { lanzouwmurl = ":lanzouwmurl"}
