[build]
  publish = "."          
  functions = ".netlify/functions"
[[redirects]]
  from = "/"
  to = "/.netlify/functions/lanzou?lanzouwmurl=:lanzouwmurl"
  status = 200
  force = true
  query = { lanzouwmurl = ":lanzouwmurl" }  # 显式传递参数