[build]
  publish = "."          
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/lanzou?lanzouwmurl=:lanzouwmurl"
  status = 200
  query = { lanzouwmurl = ":lanzouwmurl" }
