[build]
  publish = "."          # 静态文件目录
  functions = "functions" # 函数目录

# 重定向规则（关键修正）
[[redirects]]
  from = "/"     # 匹配 /lanzou/xxx
  to = "/.netlify/functions/lanzou"  # 传递完整路径
  status = 200
  force = true
