[build]
   
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/lanzou?lanzouwmurl=:lanzouwmurl"
  status = 200
  force = true
  query = { url = ":lanzouwmurl" }  # 显式传递参数
