[build]
  publish="html"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/lanzou?url=:lanzouwmurl"
  status = 302
force=true
  query = { lanzouwmurl = ":lanzouwmurl"}
