[build]
  publish="html"
  functions = "netlify/functions"

[[redirects]]
from = "/"
to = "/.netlify/functions/lanzou?url=:lanzouwmurl&type=:type"
status = 302
force = true
query = { lanzouwmurl = ":lanzouwmurl", type = ":type?" }  # 问号表示可选
